# nagios-check-supervisord
# Makefile


PHONY: docs clear build upload

docs:
	rst2html README.rst > index.html && zip docs.zip index.html

clear:
	rm -rf index.html docs.zip build dist nagios_check_supervisord.egg-info

build:
	./setup.py bdist_wheel sdist

upload:
	./setup.py bdist_wheel sdist upload

help:
	@echo "    docs:"
	@echo "        Build docs"
	@echo "    clear:"
	@echo "        Remove useless autogenerated files."
	@echo "    build:"
	@echo "        Build package."
	@echo "    upload:"
	@echo "        Upload to PyPI."
